USE QL_THAMGIADT

--Q35--
SELECT MAX(LUONG) AS LUONG_CAO_NHAT
FROM GIAOVIEN

--Q36--
SELECT *
FROM GIAOVIEN AS GV
WHERE GV.LUONG = (SELECT MAX(LUONG) FROM GIAOVIEN)

--Q37--
SELECT MAX(LUONG) AS LUONG_CAO_NHAT_HTTT
FROM GIAOVIEN AS GV
WHERE GV.MABM = 'HTTT'

--Q38--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.NGAYSINH = (SELECT MIN(NGAYSINH) FROM GIAOVIEN WHERE MABM = 'HTTT')

--Q39--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.NGAYSINH = (SELECT MAX(NGAYSINH) FROM GIAOVIEN WHERE MABM IN (SELECT MABM FROM BOMON WHERE MAKHOA = 'CNTT'))

--Q40--
SELECT GV.HOTEN, (SELECT TENKHOA FROM KHOA WHERE MAKHOA = (SELECT BM.MAKHOA FROM BOMON AS BM WHERE BM.MABM = GV.MABM)) AS TENKHOA
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(SELECT LUONG FROM GIAOVIEN)

--Q41--
SELECT *
FROM GIAOVIEN