USE QL_THAMGIADT

--Q1--
SELECT HOTEN, LUONG
FROM GIAOVIEN
WHERE PHAI = N'Nữ';

--Q2--
SELECT HOTEN, LUONG AS LUONG_TRUOC, LUONG * 1.1 AS LUONG_SAU
FROM GIAOVIEN

--Q3--
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN AS GV, KHOA AS K
WHERE (GV.HOTEN LIKE N'Nguyễn%' AND GV.LUONG >= 2000) OR (GV.MAGV = K.TRUONGKHOA AND YEAR(K.NGAYNHANCHUC) > 1995)

--Q4--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
LEFT JOIN BOMON AS BM
ON GV.MABM = BM.MABM
WHERE BM.MAKHOA = 'CNTT'

--Q5--
SELECT *
FROM BOMON AS BM
LEFT JOIN GIAOVIEN AS GV
ON GV.MAGV = BM.TRUONGBM

--Q6--
SELECT *
FROM GIAOVIEN AS GV
LEFT JOIN BOMON AS BM
ON GV.MABM = BM.MABM

--Q7--
SELECT DT.TENDT, GV.HOTEN
FROM DETAI AS DT
LEFT JOIN GIAOVIEN AS GV
ON DT.GVCNDT = GV.MAGV

--Q8--
SELECT K.TENKHOA, GV.HOTEN AS TRUONGKHOA
FROM KHOA AS K
LEFT JOIN GIAOVIEN AS GV
ON K.TRUONGKHOA = GV.MAGV

--Q9--
SELECT GV.MAGV, GV.HOTEN, GV.PHAI, GV.NGAYSINH, GV.DIACHI, GV.MABM, DT.MADT
FROM GIAOVIEN AS GV
LEFT JOIN BOMON AS BM
ON GV.MABM = BM.MABM
LEFT JOIN DETAI AS DT
ON GV.MAGV = DT.GVCNDT
WHERE BM.MABM = 'VS' AND DT.MADT = '006'

--Q10--
SELECT DT.MADT, DT.TENDT, CD.TENCD AS CHUDE, GV.HOTEN, GV.NGAYSINH, GV.DIACHI
FROM DETAI AS DT
LEFT JOIN GIAOVIEN AS GV
ON DT.GVCNDT = GV.MAGV
LEFT JOIN CHUDE AS CD
ON DT.MACD = CD.MACD
WHERE DT.CAPQL <> N'Nhà nước'

--Q11--
SELECT GV1.HOTEN, GV1.GVQLCM, GV2.HOTEN AS TENGVQLCM
FROM GIAOVIEN AS GV1
LEFT JOIN GIAOVIEN AS GV2
ON GV1.GVQLCM = GV2.MAGV

--Q12--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1
LEFT JOIN GIAOVIEN AS GV2
ON GV1.GVQLCM = GV2.MAGV
WHERE GV2.HOTEN = N'Nguyễn Thanh Tùng'

--Q13--
SELECT GV.HOTEN AS TRUONG_BM_HTTT
FROM GIAOVIEN AS GV
LEFT JOIN BOMON AS BM
ON GV.MAGV = BM.TRUONGBM
WHERE BM.MABM = 'HTTT'

--Q14--
SELECT GV.HOTEN AS GVCNDT, DT.TENDT, CD.TENCD AS CDDT
FROM GIAOVIEN AS GV
LEFT JOIN DETAI AS DT
ON GV.MAGV = DT.GVCNDT
LEFT JOIN CHUDE AS CD
ON DT.MACD = CD.MACD
WHERE CD.TENCD = N'Quản lý giáo dục'

--Q15--
SELECT CV.TENCV
FROM DETAI AS DT
LEFT JOIN CONGVIEC AS CV
ON DT.MADT = CV.MADT
WHERE (DT.TENDT = N'HTTT quản lý các trường ĐH') AND MONTH(CV.NGAYBD) = 3

--Q16--
SELECT GV1.HOTEN, GV1.GVQLCM, GV2.HOTEN AS TENGVQLCM
FROM GIAOVIEN AS GV1
LEFT JOIN GIAOVIEN AS GV2
ON GV1.GVQLCM = GV2.MAGV
WHERE GV1.GVQLCM IS NOT NULL

--Q17--
SELECT *
FROM CONGVIEC AS CV
WHERE CV.NGAYBD BETWEEN '01/01/2007' AND '08/01/2007'

--Q18--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE (GV.MABM = (SELECT MABM FROM GIAOVIEN WHERE HOTEN = N'Trần Trà Hương')) AND (GV.HOTEN <> N'Trần Trà Hương')

--Q19--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, DETAI AS DT
WHERE (GV.MAGV = BM.TRUONGBM) AND (GV.MAGV = DT.GVCNDT)

--Q20--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE (GV.MAGV = K.TRUONGKHOA) AND (GV.MAGV = BM.TRUONGBM)

--Q21--
SELECT DISTINCT BM.TRUONGBM AS MA_TRUONGBM_CNDT
FROM BOMON AS BM, DETAI AS DT
WHERE BM.TRUONGBM = DT.GVCNDT

--Q22--
SELECT DISTINCT K.TRUONGKHOA AS MA_TRUONGKHOA_CNDT
FROM KHOA AS K, DETAI AS DT
WHERE K.TRUONGKHOA = DT.GVCNDT

--Q23--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV
LEFT JOIN DETAI AS DT
ON GV.MAGV = DT.GVCNDT
WHERE (GV.MABM = 'HTTT') OR (DT.MADT = '001')

--Q24--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.MABM = (SELECT MABM FROM GIAOVIEN WHERE MAGV = '002') AND (GV.MAGV <> '002')

--Q25--
SELECT *
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MAGV = BM.TRUONGBM

--Q26--
SELECT HOTEN, LUONG
FROM GIAOVIEN