USE QL_THAMGIADT

--Q58--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT CD.MACD
	FROM CHUDE AS CD
	WHERE NOT EXISTS (
		SELECT 1
		FROM DETAI AS DT, THAMGIADT AS TG
		WHERE DT.MADT = TG.MADT AND TG.MAGV = GV.MAGV AND CD.MACD = DT.MACD
	)
)

--Q59--
SELECT DT.TENDT
FROM DETAI AS DT
WHERE NOT EXISTS (
	SELECT GV.MAGV 
	FROM GIAOVIEN AS GV
	WHERE GV.MABM = 'HTTT' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE TG.MAGV = GV.MAGV AND TG.MADT =  DT.MADT
	)
)

--Q60--
SELECT DT.TENDT
FROM DETAI AS DT
WHERE NOT EXISTS (
	SELECT GV.MAGV
	FROM GIAOVIEN AS GV,BOMON AS BM
	WHERE GV.MABM = BM.MABM AND BM.TENBOMON = N'Hệ thống thông tin' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE TG.MADT = DT.MADT AND GV.MAGV = TG.MAGV
	)
)

--Q61--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT DT.MADT
	FROM DETAI AS DT, CHUDE AS CD
	WHERE DT.MACD = CD.MACD AND CD.MACD = 'QLGD' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE GV.MAGV = TG.MAGV AND DT.MADT = TG.MADT
	)
)

--Q62--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT *
	FROM THAMGIADT AS TG1, GIAOVIEN AS GV2
	WHERE TG1.MAGV = GV2.MAGV AND GV2.HOTEN = N'Trần Trà Hương' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG2
		WHERE TG2.MADT = TG1.MADT AND GV.MAGV = TG2.MAGV
	)
)

--Q63--
SELECT DT.TENDT
FROM DETAI AS DT
WHERE NOT EXISTS (
	SELECT *
	FROM GIAOVIEN AS GV, BOMON AS BM
	WHERE GV.MABM = BM.MABM AND BM.TENBOMON = N'Hoá hữu cơ' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE TG.MAGV = GV.MAGV AND DT.MADT = TG.MADT
	)
)

--Q64--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT * 
	FROM CONGVIEC AS CV
	WHERE CV.MADT = '006' AND NOT EXISTS (
		SELECT 1 
		FROM THAMGIADT AS TG
		WHERE TG.MAGV = GV.MAGV AND TG.STT = CV.SOTT AND TG.MADT = '006'
	)
)

--Q65--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT *
	FROM DETAI AS DT, CHUDE AS CD
	WHERE DT.MACD = CD.MACD AND CD.TENCD = N'Ứng dụng công nghệ' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE TG.MAGV = GV.MAGV AND DT.MADT = TG.MADT
	)
)

--Q66--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT *
	FROM DETAI AS DT, GIAOVIEN AS GV2
	WHERE DT.GVCNDT = GV2.MAGV AND GV2.HOTEN = N'Trần Trà Hương' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE TG.MAGV = GV.MAGV AND DT.MADT = TG.MADT
	)
)

--Q67--
SELECT DT.TENDT
FROM DETAI AS DT
WHERE NOT EXISTS (
	SELECT *
	FROM BOMON AS BM, KHOA AS K, GIAOVIEN AS GV
	WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.MAKHOA = 'CNTT' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE TG.MADT = DT.MADT AND GV.MAGV = TG.MAGV
	)
)

--Q68--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT * 
	FROM CONGVIEC AS CV, DETAI AS DT
	WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE DT.MADT = TG.MADT AND GV.MAGV = TG.MAGV AND TG.STT = CV.SOTT
	)
)

--Q69--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT *
	FROM DETAI AS DT
	WHERE DT.KINHPHI > 100 AND NOT EXISTS (
		SELECT *
		FROM THAMGIADT AS TG
		WHERE TG.MADT = DT.MADT AND TG.MAGV = GV.MAGV
	)
)

--Q70--
SELECT DT.TENDT
FROM DETAI AS DT
WHERE NOT EXISTS (
	SELECT *
	FROM GIAOVIEN AS GV, KHOA AS K, BOMON AS BM
	WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Sinh học' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE TG.MAGV = GV.MAGV AND DT.MADT = TG.MADT
	)
)

--Q71--
SELECT GV.MAGV, GV.HOTEN, GV.NGAYSINH
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (
	SELECT *
	FROM CONGVIEC AS CV, DETAI AS DT
	WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Ứng dụng hóa học xanh' AND NOT EXISTS (
		SELECT 1
		FROM THAMGIADT AS TG
		WHERE CV.SOTT = TG.STT AND GV.MAGV = TG.MAGV AND DT.MADT = TG.MADT
	)
)

--Q72--
SELECT GV.MAGV, GV.HOTEN, BM.TENBOMON, NQL.HOTEN
FROM GIAOVIEN AS NQL, GIAOVIEN AS GV, BOMON AS BM
WHERE NQL.MAGV = GV.GVQLCM AND BM.MABM = NQL.MABM AND NOT EXISTS (
	SELECT *
	FROM DETAI AS DT, CHUDE AS CD
	WHERE DT.MACD = CD.MACD AND CD.TENCD = N'Nghiên cứu phát triển' AND NOT EXISTS (
		SELECT 1 
		FROM THAMGIADT AS TG
		WHERE TG.MADT = DT.MADT AND GV.MAGV = TG.MAGV
	)
)