USE QL_THAMGIADT

--Q27--
SELECT COUNT(*) AS SO_LUONG_GIAO_VIEN, SUM(LUONG) AS TONG_LUONG_GIAO_VIEN
FROM GIAOVIEN

--Q28--
SELECT MABM, COUNT(*) AS SO_LUONG_GIAO_VIEN, AVG(LUONG) AS LUONG_TRUNG_BINH
FROM GIAOVIEN
GROUP BY MABM

--Q29--
SELECT CD.TENCD, COUNT(DT.MADT) AS SO_LUONG_DT
FROM CHUDE AS CD, DETAI AS DT
WHERE CD.MACD = DT.MACD
GROUP BY CD.TENCD

--Q30--
SELECT GV.HOTEN, COUNT(TG.MADT) AS SO_LUONG_DT
FROM GIAOVIEN AS GV, THAMGIADT AS TG
WHERE GV.MAGV = TG.MAGV
GROUP BY GV.HOTEN

--Q31--
SELECT GV.HOTEN, COUNT(DT.MADT) AS SO_DETAI_LAM_CN
FROM GIAOVIEN AS GV, DETAI AS DT
WHERE GV.MAGV = DT.GVCNDT
GROUP BY GV.HOTEN

--Q32--
SELECT GV.HOTEN, COUNT(NT.MAGV) AS SO_NGUOI_THAN
FROM GIAOVIEN AS GV, NGUOITHAN AS NT
WHERE GV.MAGV = NT.MAGV
GROUP BY GV.HOTEN

--Q33--
SELECT GV.HOTEN, COUNT(TG.MADT) AS SO_LUONG_DT
FROM GIAOVIEN AS GV, THAMGIADT AS TG
WHERE GV.MAGV = TG.MAGV
GROUP BY GV.HOTEN
HAVING COUNT(TG.MADT) >= 3

--Q34--
SELECT DT.TENDT, COUNT(GV.MAGV) AS SL_GV_THAMGIADT
FROM DETAI AS DT
LEFT JOIN THAMGIADT AS TG
ON DT.MADT = TG.MADT
LEFT JOIN GIAOVIEN AS GV
ON TG.MAGV = GV.MAGV
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY DT.TENDT